### ISSUE TITLE
Error while setting up platform marantzusb

### ISSUE THREAD

**Issue by Pakast** [Imperial-Guard/Marantz_USB-Serial#1]
When restarting Home Assistant after implementing all the changes I get the following error:

`Error while setting up platform marantzusb
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/marantzusb/media_player.py", line 51, in setup_platform
    from marantz_receiver import MarantzReceiver
ModuleNotFoundError: No module named 'marantz_receiver'`

I tried adding the site-packages to both "deps/lib" and "deps/lib/python3.7", both are not working. Please note that the deps folder was empty so I had to create the underlaying folders myself.

**Comment by Imperial-Guard** [comment]
Looks like that the folder marantz_receiver can't be found, in my case it's "config/deps/lib/python3.7/site-packages/marantz_receiver/__init__.py" and "config/deps/lib/python3.7/site-packages/marantz_receiver/marantz_commands.py"

Small note which version of Home Assistant are you using? 
I'm using Home Assistant: 0.102.2 with python_version: 3.7.4

**Comment by Pakast** [comment]
I have been able to get it working by placing it in /srv/homeassistant/lib/python3.7/site-packages/. Do you think this is okay?

Home Assistant: 0.102.3, Python: 3.7.3.

**Comment by Imperial-Guard** [comment]
If everything is working then it seems to be ok. To get a better understanding are you running HassIO or Home Assistant on a Docker container?

**Comment by Pakast** [comment]
Docker container
