### ISSUE TITLE
Hardware Info

### ISSUE THREAD

**Issue by dirty-jimm** [Imperial-Guard/Marantz_USB-Serial#2]
Do you have an info on the RS232 hardware? I'm using an FTDI USB to RS232 converted, 3 wire configuration but can't get a response from the amp. Not much info online about voltage levels or RTS requirements.

**Comment by Imperial-Guard** [comment]
This was a Belkin USB to RS232 converter, I'm not using it anymore since I've changed to a Network - RS232 converter
